Repository Platzi-Master-C8/gethired-jobplacement-salaries-frontend, pull requests merged in 2022-01, with the labels that each got.

#12 Feature 11 - Add Services
  .eslintrc.js
  src/app/ListData/selectors.js
  src/app/ListData/slice.js
  src/components/FormCard/FormCard.jsx
  src/constants/index.js
  src/pages/NotFound.jsx
  src/services/salaries.js
  src/services/utilsApi.js
  webpack.config.js
Labels: enhancement, feature

#16 feature 15 - add function for change of currency
  src/services/currency.js
  src/services/http.js
  src/services/salaries.js
Labels: feature

#17 Feature 14 Getting Seniority levels from the endpoint
  src/app/ListData/selectors.js
  src/app/ListData/slice.js
  src/components/FormCard/FormCard.jsx
  src/constants/index.js
  src/services/salaries.js
Labels: feature

#18 Feature 13 integrate salaries chart with backend - Issue #13
  src/app/CalculateSalary/selectors.js
  src/app/CalculateSalary/slice.js
  src/components/Charts/NormalDistributionChart.jsx
  src/components/FormCard/FormCard.jsx
  src/components/TabCalculate/TabCalculate.jsx
  src/components/TabCompare/TabCompare.jsx
  src/constants/mockData.js
  src/services/http.js
  src/services/salaries.js
Labels: feature

#22 Feature 19 - Change select in Job Title and Technologies to Autocomplete
  src/app/CalculateSalary/slice.js
  src/components/FormCard/FormCard.jsx
  src/components/TabCalculate/TabCalculate.jsx
Labels: enhancement, componets

#25 Feature 24 - Integrate CompareTab forms to redux and send real data to API to get salaries comparison data
  src/app/CalculateSalary/selectors.js
  src/app/CalculateSalary/slice.js
  src/components/TabCompare/TabCompare.jsx
Labels: feature

#27 Feature 26 - Show error messages when the query for the chart data to the API fails
  package.json
  src/app/CalculateSalary/selectors.js
  src/app/CalculateSalary/slice.js
  src/components/Commons/SnackbarMessage/SnackbarMessage.jsx
  src/components/TabCalculate/TabCalculate.jsx
  src/components/TabCompare/TabCompare.jsx
  src/pages/Salaries.jsx
  yarn.lock
Labels: enhancement, feature, componets

#30 feat: add .env file
  .env.example
  .gitignore
  package.json
  src/constants/index.js
  src/routes/index.jsx
  src/services/salaries.js
  webpack.config.js
  yarn.lock
Labels: enhancement, feature

#31 Feature 28 - Exchange functions
  package.json
  src/libs/exchange/exchange.js
  src/libs/exchange/exchange.spec.js
  src/libs/exchange/index.js
  src/services/currency.js
  webpack.config.js
Labels: enhancement, feature

#21 Feature 20 - Add select for currencies
  src/app/CalculateSalary/selectors.js
  src/app/CalculateSalary/slice.js
  src/app/ListData/index.js
  src/app/ListData/selectors.js
  src/app/ListData/slice.js
  src/app/rootReducer.js
  src/components/Charts/NormalDistributionChart.jsx
  src/components/Commons/Select/Select.jsx
  src/components/Currencies/Currencies.jsx
  src/components/Currencies/index.js
  src/components/FormCard/FormCard.jsx
  src/components/TabCalculate/TabCalculate.jsx
  src/components/TabCompare/TabCompare.jsx
  src/constants/index.js
  src/pages/Salaries.jsx
  src/services/currency.js
Labels: enhancement, componets
